### ISSUE TITLE
how to use the web application?

### ISSUE THREAD

**Issue by LiuCMU** [yuqwu/Replace-Anything#2]
Hi, I got the follwoing webpabe after running `bentoml serve`. This interface is different that the cartoon in the ReadMe. Could you telll me how to try out the replace function?

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/60156077/236711959-9942fe1d-7701-4383-9e29-68942035fb03.png">

**Comment by LiuCMU** [comment]
Here is a little followup on the questin. After uploading the penguin iamge (attached) to the inpaint API, I got the following response: What does the response mean? Thank you very much!
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/60156077/236712420-1ed0750d-f038-4ceb-809e-0c925e70fad7.png">
![pengui](https://user-images.githubusercontent.com/60156077/236712425-8877dc51-8f77-4b08-8536-04eb18fa7ede.png)

**Comment by yuqwu** [comment]
@LiuCMU You can access the WebUI through the /interface endpoint. The root / path is the Swagger debugging page provided by BentoML. I will update the README to clarify the WebUI path.

**Comment by LiuCMU** [comment]
sorry, I didn't get it. Could you explain how I adjust the command `bentoml serve` to use the /interface endpoint as you mentioned above? thanks!

**Comment by ssheng** [comment]
No, you won't need to modify the `serve` command but visit `http://0.0.0.0:3000/interface` instead.

**Comment by LiuCMU** [comment]
what works, thank you very much!
